// Code generated by hertz generator.

package task

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _eventMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dailyeventMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _eventlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _eventtableMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _eventtypelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _medalsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _allmedalsMw() []app.HandlerFunc {
	// your code...
	return nil
}
