// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	task "backend/biz/router/task"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	task.Register(r)
}
