// Code generated by hertz generator.

package task

import (
	task "backend/biz/model/task"
	"backend/biz/service"
	consts2 "backend/consts"
	"backend/pack"
	"context"
	"strconv"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// AllMedals .
// @router api/medals/all [POST]
func AllMedals(ctx context.Context, c *app.RequestContext) {
	var err error
	var req task.AllMedalsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, err, consts2.ErrorBind)
		return
	}
	resp := new(task.AllMedalsResp)
	resp.Base = pack.BuildBaseReap(nil)
	userResp, err := service.NewTaskService(ctx, c).AllMedals(ctx, &req)
	if err != nil {
		pack.SendFailResponse(c, err, consts2.ERROR)
		return
	}
	sorts, err := strconv.Atoi(req.MedalSorts)
	if err != nil {
		pack.SendFailResponse(c, err, consts2.ERROR)
		return
	}
	resp.Data = pack.WrapOlympicsData(userResp, sorts)
	pack.SendResponse(c, resp, consts.StatusOK)
}

// DailyEvent .
// @router api/event/daily [GET]
func DailyEvent(ctx context.Context, c *app.RequestContext) {
	var err error
	var req task.DailyEventReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, err, consts2.ErrorBind)
		return
	}
	resp := new(task.DailyEventResp)
	resp.Base = pack.BuildBaseReap(nil)
	userResp, err := service.NewTaskService(ctx, c).DailyEvent(ctx, &req)
	if err != nil {
		pack.SendFailResponse(c, err, consts2.ERROR)
		return
	}
	resp.Data = pack.ConvertEvent(userResp)
	pack.SendResponse(c, resp, consts.StatusOK)
}

// EventTypeList .
// @router api/event/typelist [POST]
func EventTypeList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req task.EventTypeListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(task.EventTypeListResp)
	userResp, err := service.NewTaskService(ctx, c).EventTypeList(ctx, &req)
	if err != nil {
		pack.SendFailResponse(c, err, consts2.ERROR)
		return
	}
	resp.Data, err = pack.WrapEventTypeList(userResp)
	if err != nil {
		pack.SendFailResponse(c, err, consts2.ERROR)
		return
	}
	pack.SendResponse(c, resp, consts.StatusOK)
}

// EventTable .
// @router api/event/table [GET]
func EventTable(ctx context.Context, c *app.RequestContext) {
	var err error
	var req task.EventTableReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(task.EventTableResp)

	c.JSON(consts.StatusOK, resp)
}

// EventList .
// @router api/event/list [DELETE]
func EventList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req task.EventListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(task.EventListResp)

	c.JSON(consts.StatusOK, resp)
}
